container:
  image: ruby:latest

task:
  name: RSpec
  script:
    - gem install rspec
    - cd rspec
    - rspec --format json --out rspec.json
  always:
    artifacts:
      path: rspec/rspec.json
      type: text/json
      format: rspec
